In [1]:
import re
import pandas as pd 
import numpy as np 
import string
import nltk
import os
import warnings 
warnings.filterwarnings("ignore", category=DeprecationWarning)
from sklearn import tree
from sklearn import model_selection, preprocessing, linear_model, naive_bayes, metrics, svm
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn import decomposition, ensemble
from matplotlib import * 
import pickle

#import pandas, xgboost, numpy, textblob, string
#from keras.preprocessing import text, sequence
#from keras import layers, models, optimizers

### localhost_access

In [2]:
lines=[]
filename = []

In [3]:
inputdir = "C:\\Users\\vk00595236\\Documents\\DataScience\\Log Analytics\\log files\\log files\\Tomcat\\localhost_access\\"
filelist = os.listdir(inputdir)
for i in filelist:
    infile=inputdir+i
    openFile = open(infile, 'r')
    lines.append(openFile.read())
    filename.append(i)
    #print(filelist)
   
    

In [4]:
df_localhost_access=pd.DataFrame({'lines':lines,'filename':filename})

In [5]:
df_localhost_access

lines  \
0   0:0:0:0:0:0:0:1 - - [18/Mar/2015:09:51:32 +053...   
1   10.23.225.247 - - [24/Mar/2015:12:40:00 +0530]...   
2   10.23.225.247 - - [25/Mar/2015:12:15:07 +0530]...   
3   172.16.192.94 - - [26/Mar/2015:00:08:32 +0530]...   
4   10.23.225.168 - - [28/Mar/2015:10:29:08 +0530]...   
5   10.23.227.11 - - [31/Mar/2015:01:06:43 +0530] ...   
6   172.19.132.26 - - [01/Apr/2015:09:26:25 +0530]...   
7   10.53.99.12 - - [07/Apr/2015:12:19:23 +0530] "...   
8   10.53.50.32 - - [09/Apr/2015:09:46:50 +0530] "...   
9   10.53.50.151 - - [16/Apr/2015:10:16:22 +0530] ...   
10  10.53.50.151 - - [17/Apr/2015:10:16:28 +0530] ...   
11  10.53.50.151 - - [20/Apr/2015:10:16:21 +0530] ...   
12  10.56.161.93 - - [22/Apr/2015:08:41:51 +0530] ...   
13  172.16.192.94 - - [28/Apr/2015:03:07:50 +0530]...   
14  10.53.254.13 - - [29/Apr/2015:11:56:53 +0530] ...   
15  172.17.2.111 - - [30/Apr/2015:11:27:04 +0530] ...   
16  172.17.1.150 - - [04/May/2015:10:02:58 +0530] ...   
17  10.53.50.50 - - [06/May/2015:09:41:14 +0530] "...   
18  10.53.254.7 - - [07/May/2015:12:52:53 +0530] "...   
19  172.16.192.94 - - [12/May/2015:05:29:22 +0530]...   
20  172.16.192.94 - - [13/May/2015:05:36:57 +0530]...   
21  172.16.192.94 - - [15/May/2015:05:14:10 +0530]...   
22  10.56.160.44 - - [19/May/2015:09:36:36 +0530] ...   
23  10.53.254.5 - - [20/May/2015:09:09:03 +0530] "...   
24  10.53.50.50 - - [21/May/2015:09:39:58 +0530] "...   
25  172.16.192.94 - - [25/May/2015:02:09:43 +0530]...   
26  172.16.192.94 - - [26/May/2015:02:12:50 +0530]...   
27  172.16.192.94 - - [28/May/2015:02:40:59 +0530]...   
28  172.16.192.94 - - [29/May/2015:02:48:47 +0530]...   
29  10.53.50.77 - - [03/Jun/2015:11:56:39 +0530] "...   
..                                                ...   
45  172.16.192.94 - - [26/Aug/2015:02:48:51 +0530]...   
46  172.16.192.94 - - [31/Aug/2015:05:09:17 +0530]...   
47  172.16.192.94 - - [01/Sep/2015:05:25:18 +0530]...   
48  172.16.192.94 - - [28/Sep/2015:00:04:33 +0530]...   
49  172.19.82.9 - - [03/Dec/2015:10:36:46 +0530] "...   
50  172.16.192.94 - - [04/Jan/2016:01:25:19 +0530]...   
51  172.19.82.133 - - [03/May/2016:10:23:42 +0530]...   
52  10.59.247.254 - - [25/May/2016:13:18:19 +0530]...   
53  10.53.223.50 - - [02/Jun/2016:12:15:56 +0530] ...   
54  172.16.192.94 - - [09/Jun/2016:10:17:59 +0530]...   
55  172.19.84.52 - - [04/Jul/2016:09:54:18 +0530] ...   
56  172.19.84.52 - - [05/Jul/2016:09:39:27 +0530] ...   
57  172.16.192.94 - - [08/Jul/2016:14:09:18 +0530]...   
58  10.59.254.3 - - [13/Sep/2016:19:44:58 +0530] "...   
59  172.16.192.94 - - [02/Nov/2016:01:11:25 +0530]...   
60  172.16.192.94 - - [03/Nov/2016:01:14:45 +0530]...   
61  172.16.192.94 - - [04/Nov/2016:01:18:28 +0530]...   
62  10.53.223.50 - - [22/Dec/2016:11:27:38 +0530] ...   
63  10.53.223.11 - - [19/Apr/2017:14:55:55 +0530] ...   
64  10.53.50.58 - tomcat [25/Sep/2018:19:23:56 +05...   
65  10.53.50.58 - - [28/Sep/2018:11:21:21 +0530] "...   
66  10.53.50.44 - - [01/Oct/2018:09:43:36 +0530] "...   
67  10.53.50.58 - - [03/Oct/2018:10:08:54 +0530] "...   
68  10.53.50.58 - - [04/Oct/2018:11:40:02 +0530] "...   
69  10.53.50.58 - - [10/Oct/2018:17:33:47 +0530] "...   
70  10.53.50.58 - - [31/Oct/2018:13:11:50 +0530] "...   
71  10.53.50.44 - - [08/Nov/2018:11:37:11 +0530] "...   
72  10.53.50.58 - - [12/Nov/2018:10:57:20 +0530] "...   
73  10.53.50.58 - - [13/Nov/2018:09:25:00 +0530] "...   
74  10.53.50.58 - - [20/Nov/2018:10:31:52 +0530] "...   

                               filename  
0   localhost_access_log.2015-03-18.txt  
1   localhost_access_log.2015-03-24.txt  
2   localhost_access_log.2015-03-25.txt  
3   localhost_access_log.2015-03-26.txt  
4   localhost_access_log.2015-03-28.txt  
5   localhost_access_log.2015-03-31.txt  
6   localhost_access_log.2015-04-01.txt  
7   localhost_access_log.2015-04-07.txt  
8   localhost_access_log.2015-04-09.txt  
9   localhost_access_log.2015-04-16.txt  
10  localhost_access_log.2015-04-17.txt  
11  local

In [6]:
df_localhost_access['clean_line'] = df_localhost_access['lines'].str.replace("[^a-zA-Z0-9]", " ")

In [7]:
df_localhost_access['clean_line'] = df_localhost_access['clean_line'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))

In [8]:
df_localhost_access['label'] = '1'

In [9]:
len(df_localhost_access['clean_line'])

75

### Localhost

In [10]:
lines=[]
filename = []

In [11]:
inputdir = "C:\\Users\\vk00595236\\Documents\\DataScience\\Log Analytics\\log files\\log files\\Tomcat\\localhost\\"
filelist = os.listdir(inputdir)
for i in filelist:
    infile=inputdir+i
    openFile = open(infile, 'r')
    lines.append(openFile.read())
    filename.append(i)
    #print(filelist)
   
    

In [12]:
df_localhost=pd.DataFrame({'lines':lines,'filename':filename})

In [13]:
df_localhost

lines  \
0   Mar 24, 2015 12:38:00 PM org.apache.catalina.c...   
1   Mar 31, 2015 1:06:43 AM org.apache.catalina.co...   
2   Apr 01, 2015 9:37:25 AM org.apache.catalina.co...   
3   Apr 07, 2015 12:19:09 PM org.apache.catalina.c...   
4   Apr 09, 2015 3:55:36 PM org.apache.catalina.co...   
5   Apr 10, 2015 1:51:59 PM org.apache.catalina.co...   
6   Apr 17, 2015 11:01:26 AM org.apache.catalina.c...   
7   Apr 22, 2015 10:46:51 AM org.apache.catalina.c...   
8   May 25, 2015 10:07:05 AM org.apache.catalina.c...   
9   May 26, 2015 10:51:23 AM org.apache.catalina.c...   
10  Aug 04, 2015 4:06:21 PM org.apache.catalina.co...   
11  Jun 02, 2016 2:01:34 PM org.apache.catalina.co...   
12  Sep 13, 2016 7:44:11 PM org.apache.catalina.co...   
13  Nov 02, 2016 3:55:37 PM org.apache.catalina.co...   
14  Nov 03, 2016 1:13:21 PM org.apache.catalina.co...   
15  Nov 04, 2016 1:31:50 PM org.apache.catalina.co...   
16  Sep 25, 2018 7:19:29 PM org.apache.catalina.co...   
17  Sep 28, 2018 5:41:21 PM org.apache.catalina.co...   
18  Oct 01, 2018 9:43:49 AM org.apache.catalina.co...   
19  Oct 03, 2018 10:01:52 AM org.apache.catalina.c...   
20  Oct 04, 2018 11:40:08 AM org.apache.catalina.c...   
21  Oct 05, 2018 12:51:49 PM org.apache.catalina.c...   
22  Oct 09, 2018 10:08:21 AM org.apache.catalina.c...   
23  Oct 10, 2018 5:28:14 PM org.apache.catalina.co...   
24  Oct 15, 2018 10:02:19 AM org.apache.catalina.c...   
25  Oct 25, 2018 11:12:51 AM org.apache.catalina.c...   
26  Oct 30, 2018 9:13:48 AM org.apache.catalina.co...   
27  Oct 31, 2018 1:10:07 PM org.apache.catalina.co...   
28  Nov 02, 2018 4:49:59 PM org.apache.catalina.co...   
29  Nov 08, 2018 12:41:43 PM org.apache.catalina.c...   
30  Nov 09, 2018 9:17:10 AM org.apache.catalina.co...   

                    filename  
0   localhost.2015-03-24.log  
1   localhost.2015-03-31.log  
2   localhost.2015-04-01.log  
3   localhost.2015-04-07.log  
4   localhost.2015-04-09.log  
5   localhost.2015-04-10.log  
6   localhost.2015-04-17.log  
7   localhost.2015-04-22.log  
8   localhost.2015-05-25.log  
9   localhost.2015-05-26.log  
10  localhost.2015-08-04.log  
11  localhost.2016-06-02.log  
12  localhost.2016-09-13.log  
13  localhost.2016-11-02.log  
14  localhost.2016-11-03.log  
15  localhost.2016-11-04.log  
16  localhost.2018-09-25.log  
17  localhost.2018-09-28.log  
18  localhost.2018-10-01.log  
19  localhost.2018-10-03.log  
20  localhost.2018-10-04.log  
21  localhost.2018-10-05.log  
22  localhost.2018-10-09.log  
23  localhost.2018-10-10.log  
24  localhost.2018-10-15.log  
25  localhost.2018-10-25.log  
26  localhost.2018-10-30.log  
27  localhost.2018-10-31.log  
28  localhost.2018-11-02.log  
29  localhost.2018-11-08.log  
30  localhost.2018-11-09.log

In [14]:
df_localhost['clean_line'] = df_localhost['lines'].str.replace("[^a-zA-Z0-9]", " ")

In [15]:
df_localhost['clean_line'] = df_localhost['clean_line'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))

In [16]:
df_localhost['label'] = '2'

In [17]:
len(df_localhost['clean_line'])

31

### catalina

In [18]:
lines=[]
filename = [] 

In [19]:
inputdir = "C:\\Users\\vk00595236\\Documents\\DataScience\\Log Analytics\\log files\\log files\\Tomcat\\catalina\\"
filelist = os.listdir(inputdir)
for i in filelist:
    infile=inputdir+i
    openFile = open(infile, 'r')
    lines.append(openFile.read())
    filename.append(i)
    #print(filelist)
   
    

In [20]:
type(filename)

list

In [21]:
df_catalina=pd.DataFrame({'lines':lines,'filename':filename})

In [22]:
df_catalina

lines                 filename
0   Mar 16, 2015 11:30:42 AM org.apache.catalina.c...  catalina.2015-03-16.log
1   Mar 17, 2015 11:27:28 AM org.apache.catalina.c...  catalina.2015-03-17.log
2   Mar 18, 2015 9:50:25 AM org.apache.catalina.co...  catalina.2015-03-18.log
3   Mar 19, 2015 4:22:52 PM org.apache.catalina.co...  catalina.2015-03-19.log
4   Mar 24, 2015 12:37:50 PM org.apache.catalina.s...  catalina.2015-03-24.log
5   Mar 25, 2015 11:59:37 AM org.apache.catalina.c...  catalina.2015-03-25.log
6   Mar 26, 2015 8:35:40 AM org.springframework.we...  catalina.2015-03-26.log
7   Mar 28, 2015 10:29:09 AM org.springframework.w...  catalina.2015-03-28.log
8   Mar 30, 2015 5:41:39 PM org.apache.catalina.st...  catalina.2015-03-30.log
9   Mar 31, 2015 1:06:43 AM org.hibernate.cfg.Conf...  catalina.2015-03-31.log
10  Apr 01, 2015 10:59:14 AM org.apache.coyote.Abs...  catalina.2015-04-01.log
11  Apr 07, 2015 12:19:00 PM org.apache.catalina.c...  catalina.2015-04-07.log
12  Apr 09, 2015 12:13:44 PM org.hibernate.cfg.ann...  catalina.2015-04-09.log
13  Apr 10, 2015 1:16:10 PM org.springframework.we...  catalina.2015-04-10.log
14  Apr 14, 2015 2:06:08 PM org.apache.coyote.Abst...  catalina.2015-04-14.log
15  Apr 16, 2015 11:15:03 AM org.apache.coyote.Abs...  catalina.2015-04-16.log
16  Apr 17, 2015 11:01:25 AM org.apache.coyote.Abs...  catalina.2015-04-17.log
17  Apr 20, 2015 10:57:34 AM org.springframework.w...  catalina.2015-04-20.log
18  Apr 21, 2015 1:27:42 PM org.springframework.we...  catalina.2015-04-21.log
19  Apr 22, 2015 10:46:49 AM org.hibernate.cfg.Con...  catalina.2015-04-22.log
20  Apr 23, 2015 9:12:51 AM org.apache.coyote.Abst...  catalina.2015-04-23.log
21  Apr 27, 2015 1:30:03 PM org.apache.coyote.Abst...  catalina.2015-04-27.log
22  Apr 28, 2015 3:49:37 PM org.apache.coyote.Abst...  catalina.2015-04-28.log
23  Apr 29, 2015 11:52:31 AM org.apache.coyote.Abs...  catalina.2015-04-29.log
24  Apr 30, 2015 3:22:05 PM org.springframework.we...  catalina.2015-04-30.log
25  May 04, 2015 5:22:41 PM org.apache.coyote.Abst...  catalina.2015-05-04.log
26  May 05, 2015 10:45:20 AM org.hibernate.cfg.ann...  catalina.2015-05-05.log
27  May 06, 2015 9:40:22 AM org.apache.catalina.co...  catalina.2015-05-06.log
28  May 07, 2015 12:46:07 PM org.apache.coyote.Abs...  catalina.2015-05-07.log
29  May 08, 2015 1:33:21 PM org.apache.catalina.st...  catalina.2015-05-08.log
..                                                ...                      ...
50  Nov 03, 2016 1:13:21 PM org.apache.catalina.lo...  catalina.2016-11-03.log
51  Nov 04, 2016 1:31:50 PM org.apache.catalina.co...  catalina.2016-11-04.log
52  Nov 30, 2016 11:42:30 AM org.apache.catalina.s...  catalina.2016-11-30.log
53  Dec 06, 2016 2:58:54 PM org.apache.catalina.co...  catalina.2016-12-06.log
54  Dec 12, 2016 10:55:55 AM org.apache.catalina.c...  catalina.2016-12-12.log
55  Dec 22, 2016 11:26:10 AM org.apache.catalina.s...  catalina.2016-12-22.log
56  May 11, 2017 1:50:55 PM org.apache.catalina.st...  catalina.2017-05-11.log
57  Jul 07, 2017 4:16:14 PM org.apache.catalina.co...  catalina.2017-07-07.log
58  Jul 16, 2017 12:25:32 PM org.apache.catalina.c...  catalina.2017-07-16.log
59  Jul 17, 2017 9:26:53 AM org.apache.catalina.co...  catalina.2017-07-17.log
60  Jul 18, 2017 4:05:48 PM org.apache.catalina.co...  catalina.2017-07-18.log
61  Jul 20, 2017 11:04:50 AM org.apache.catalina.c...  catalina.2017-07-20.log
62  Jul 26, 2017 12:01:05 AM org.apache.coyote.htt...  catalina.2017-07-26.log
63  Jul 28, 2017 3:58:05 PM org.apache.catalina.co...  catalina.2017-07-28.log
64  Aug 02, 2017 12:15:32 PM org.apache.catalina.c...  catalina.2017-08-02.log
65  Sep 25, 2018 7:19:14 PM org.apache.catalina.co...  catalina.2018-09-25.log
66  Oct 03, 2018 10:01:46 AM org.apache.catalina.c...  catalina.2018-10-03.log
67  Oct 04, 2018 11:40:08 AM org.apache.catalina.c...  catalina.2018-10-04.log
68  Oct 09, 2018 12:27:45 PM org.apache.catalina.c...  catalina.2018-10-09.log
69  Oct 10, 2018 12

In [23]:
df_catalina.shape

(80, 2)

In [24]:
df_catalina['clean_line'] = df_catalina['lines'].str.replace("[^a-zA-Z0-9]", " ")

In [25]:
df_catalina['clean_line'] = df_catalina['clean_line'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))

In [26]:
df_catalina['label'] = '3'

In [27]:
len(df_catalina['clean_line'])

80

### Informatica ### 

In [28]:
lines=[]
filename = [] 

In [29]:
inputdir = "C:\\Users\\vk00595236\\Documents\\DataScience\\Log Analytics\\log files\\log files\\Informatica\\"
filelist = os.listdir(inputdir)
for i in filelist:
    infile=inputdir+i
    openFile = open(infile, 'r')
    lines.append(openFile.read())
    filename.append(i)
    #print(filelist)
   
    

In [30]:
type(filename)

list

In [31]:
df_informatica=pd.DataFrame({'lines':lines,'filename':filename})

In [32]:
df_informatica

lines  \
0   DIRECTOR> VAR_27028 Use override value [/edwet...   
1   DIRECTOR> VAR_27028 Use override value [/edwet...   
2   DIRECTOR> VAR_27028 Use override value [/edwet...   
3   DIRECTOR> VAR_27028 Use override value [/edwet...   
4   DIRECTOR> VAR_27028 Use override value [/edwet...   
5   DIRECTOR> VAR_27028 Use override value [/edwet...   
6   DIRECTOR> VAR_27028 Use override value [/edwet...   
7   DIRECTOR> VAR_27028 Use override value [/edwet...   
8   DIRECTOR> VAR_27028 Use override value [/edwet...   
9   DIRECTOR> VAR_27028 Use override value [/edwet...   
10  DIRECTOR> VAR_27028 Use override value [/edwet...   
11  DIRECTOR> VAR_27028 Use override value [/edwet...   
12  DIRECTOR> VAR_27028 Use override value [/edwet...   
13  DIRECTOR> VAR_27028 Use override value [/edwet...   
14  DIRECTOR> VAR_27028 Use override value [/edwet...   
15  DIRECTOR> VAR_27028 Use override value [/edwet...   
16  DIRECTOR> VAR_27028 Use override value [/edwet...   
17  DIRECTOR> VAR_27028 Use override value [/edwet...   
18  DIRECTOR> VAR_27028 Use override value [/edwet...   
19  DIRECTOR> VAR_27028 Use override value [/edwet...   
20  DIRECTOR> VAR_27028 Use override value [/edwet...   
21  DIRECTOR> VAR_27028 Use override value [/edwet...   
22  DIRECTOR> VAR_27028 Use override value [/edwet...   
23  DIRECTOR> VAR_27028 Use override value [/edwet...   
24  DIRECTOR> VAR_27028 Use override value [/edwet...   
25  DIRECTOR> VAR_27028 Use override value [/edwet...   
26  DIRECTOR> VAR_27028 Use override value [/edwet...   
27  DIRECTOR> VAR_27028 Use override value [/edwet...   
28  DIRECTOR> VAR_27028 Use override value [/edwet...   
29  DIRECTOR> VAR_27028 Use override value [/edwet...   
..                                                ...   
51  DIRECTOR> VAR_27028 Use override value [/edwet...   
52  DIRECTOR> VAR_27028 Use override value [/edwet...   
53  DIRECTOR> VAR_27028 Use override value [/edwet...   
54  DIRECTOR> VAR_27028 Use override value [/edwet...   
55  DIRECTOR> VAR_27028 Use override value [/edwet...   
56  DIRECTOR> VAR_27028 Use override value [/edwet...   
57  DIRECTOR> VAR_27028 Use override value [/edwet...   
58  DIRECTOR> VAR_27028 Use override value [/edwet...   
59  DIRECTOR> VAR_27028 Use override value [/edwet...   
60  DIRECTOR> VAR_27028 Use override value [/edwet...   
61  DIRECTOR> VAR_27028 Use override value [/edwet...   
62  DIRECTOR> VAR_27028 Use override value [/edwet...   
63  DIRECTOR> VAR_27093 Info: Override variable [m...   
64  DIRECTOR> VAR_27028 Use override value [/edwet...   
65  DIRECTOR> VAR_27028 Use override value [/edwet...   
66  DIRECTOR> VAR_27028 Use override value [/edwet...   
67  DIRECTOR> VAR_27028 Use override value [/edwet...   
68  DIRECTOR> VAR_27028 Use override value [/edwet...   
69  DIRECTOR> VAR_27028 Use override value [/edwet...   
70  DIRECTOR> VAR_27028 Use override value [/edwet...   
71  DIRECTOR> VAR_27028 Use override value [/edwet...   
72  DIRECTOR> VAR_27028 Use override value [/edwet...   
73  DIRECTOR> VAR_27028 Use override value [/edwet...   
74  DIRECTOR> VAR_27028 Use override value [/edwet...   
75  DIRECTOR> VAR_27028 Use override value [/edwet...   
76  DIRECTOR> VAR_27028 Use override value [/edwet...   
77  DIRECTOR> VAR_27028 Use override value [/edwet...   
78  DIRECTOR> VAR_27028 Use override value [/edwet...   
79  DIRECTOR> VAR_27028 Use override value [/edwet...   
80  DIRECTOR> VAR_27028 Use override value [/edwet...   

                                        filename  
0                     s_BCC_LEGACY_PARAM_EXT.log  
1                        s_BCC_OPOM_ARBR_MAP.log  
2                                 s_cr302085.log  
3             s_d_FILE_EWBB00430D_SOMSINCTXN.log  
4            s_d_FILE_EWBB00510D_SOMSCUSTTXN.log  
5            s_d_FILE_EWBB00520D_SOMSCUSTTXN.log  
6          s_d_FILE_EWBB00530D_SOMSCUSTTXN_4.log  
7                          s_d_TEDW_BCC_CUST.log  
8                          s_d_TEDW_BCC_SUBS.log  
9  

In [33]:
df_informatica.shape

(81, 2)

In [34]:
df_informatica['clean_line'] = df_informatica['lines'].str.replace("[^a-zA-Z0-9]", " ")

In [35]:
df_informatica['clean_line'] = df_informatica['clean_line'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))

In [36]:
df_informatica['label'] = '4'

In [37]:
len(df_informatica['clean_line'])

81

## combine all four dfs

In [38]:
df1 = pd.DataFrame
df2 = pd.DataFrame
df_final = pd.DataFrame

In [39]:
df1 = df1.append(df_localhost_access,df_localhost)
df2 = df2.append(df1,df_catalina)
df_final = df_final.append(df2,df_informatica)

In [40]:
df_final.reset_index

<bound method DataFrame.reset_index of                                                 lines  \
0   0:0:0:0:0:0:0:1 - - [18/Mar/2015:09:51:32 +053...   
1   10.23.225.247 - - [24/Mar/2015:12:40:00 +0530]...   
2   10.23.225.247 - - [25/Mar/2015:12:15:07 +0530]...   
3   172.16.192.94 - - [26/Mar/2015:00:08:32 +0530]...   
4   10.23.225.168 - - [28/Mar/2015:10:29:08 +0530]...   
5   10.23.227.11 - - [31/Mar/2015:01:06:43 +0530] ...   
6   172.19.132.26 - - [01/Apr/2015:09:26:25 +0530]...   
7   10.53.99.12 - - [07/Apr/2015:12:19:23 +0530] "...   
8   10.53.50.32 - - [09/Apr/2015:09:46:50 +0530] "...   
9   10.53.50.151 - - [16/Apr/2015:10:16:22 +0530] ...   
10  10.53.50.151 - - [17/Apr/2015:10:16:28 +0530] ...   
11  10.53.50.151 - - [20/Apr/2015:10:16:21 +0530] ...   
12  10.56.161.93 - - [22/Apr/2015:08:41:51 +0530] ...   
13  172.16.192.94 - - [28/Apr/2015:03:07:50 +0530]...   
14  10.53.254.13 - - [29/Apr/2015:11:56:53 +0530] ...   
15  172.17.2.111 - - [30/Apr/2015:11:27:04 +0530]

In [41]:
df_final[:]

lines  \
0   0:0:0:0:0:0:0:1 - - [18/Mar/2015:09:51:32 +053...   
1   10.23.225.247 - - [24/Mar/2015:12:40:00 +0530]...   
2   10.23.225.247 - - [25/Mar/2015:12:15:07 +0530]...   
3   172.16.192.94 - - [26/Mar/2015:00:08:32 +0530]...   
4   10.23.225.168 - - [28/Mar/2015:10:29:08 +0530]...   
5   10.23.227.11 - - [31/Mar/2015:01:06:43 +0530] ...   
6   172.19.132.26 - - [01/Apr/2015:09:26:25 +0530]...   
7   10.53.99.12 - - [07/Apr/2015:12:19:23 +0530] "...   
8   10.53.50.32 - - [09/Apr/2015:09:46:50 +0530] "...   
9   10.53.50.151 - - [16/Apr/2015:10:16:22 +0530] ...   
10  10.53.50.151 - - [17/Apr/2015:10:16:28 +0530] ...   
11  10.53.50.151 - - [20/Apr/2015:10:16:21 +0530] ...   
12  10.56.161.93 - - [22/Apr/2015:08:41:51 +0530] ...   
13  172.16.192.94 - - [28/Apr/2015:03:07:50 +0530]...   
14  10.53.254.13 - - [29/Apr/2015:11:56:53 +0530] ...   
15  172.17.2.111 - - [30/Apr/2015:11:27:04 +0530] ...   
16  172.17.1.150 - - [04/May/2015:10:02:58 +0530] ...   
17  10.53.50.50 - - [06/May/2015:09:41:14 +0530] "...   
18  10.53.254.7 - - [07/May/2015:12:52:53 +0530] "...   
19  172.16.192.94 - - [12/May/2015:05:29:22 +0530]...   
20  172.16.192.94 - - [13/May/2015:05:36:57 +0530]...   
21  172.16.192.94 - - [15/May/2015:05:14:10 +0530]...   
22  10.56.160.44 - - [19/May/2015:09:36:36 +0530] ...   
23  10.53.254.5 - - [20/May/2015:09:09:03 +0530] "...   
24  10.53.50.50 - - [21/May/2015:09:39:58 +0530] "...   
25  172.16.192.94 - - [25/May/2015:02:09:43 +0530]...   
26  172.16.192.94 - - [26/May/2015:02:12:50 +0530]...   
27  172.16.192.94 - - [28/May/2015:02:40:59 +0530]...   
28  172.16.192.94 - - [29/May/2015:02:48:47 +0530]...   
29  10.53.50.77 - - [03/Jun/2015:11:56:39 +0530] "...   
..                                                ...   
51  DIRECTOR> VAR_27028 Use override value [/edwet...   
52  DIRECTOR> VAR_27028 Use override value [/edwet...   
53  DIRECTOR> VAR_27028 Use override value [/edwet...   
54  DIRECTOR> VAR_27028 Use override value [/edwet...   
55  DIRECTOR> VAR_27028 Use override value [/edwet...   
56  DIRECTOR> VAR_27028 Use override value [/edwet...   
57  DIRECTOR> VAR_27028 Use override value [/edwet...   
58  DIRECTOR> VAR_27028 Use override value [/edwet...   
59  DIRECTOR> VAR_27028 Use override value [/edwet...   
60  DIRECTOR> VAR_27028 Use override value [/edwet...   
61  DIRECTOR> VAR_27028 Use override value [/edwet...   
62  DIRECTOR> VAR_27028 Use override value [/edwet...   
63  DIRECTOR> VAR_27093 Info: Override variable [m...   
64  DIRECTOR> VAR_27028 Use override value [/edwet...   
65  DIRECTOR> VAR_27028 Use override value [/edwet...   
66  DIRECTOR> VAR_27028 Use override value [/edwet...   
67  DIRECTOR> VAR_27028 Use override value [/edwet...   
68  DIRECTOR> VAR_27028 Use override value [/edwet...   
69  DIRECTOR> VAR_27028 Use override value [/edwet...   
70  DIRECTOR> VAR_27028 Use override value [/edwet...   
71  DIRECTOR> VAR_27028 Use override value [/edwet...   
72  DIRECTOR> VAR_27028 Use override value [/edwet...   
73  DIRECTOR> VAR_27028 Use override value [/edwet...   
74  DIRECTOR> VAR_27028 Use override value [/edwet...   
75  DIRECTOR> VAR_27028 Use override value [/edwet...   
76  DIRECTOR> VAR_27028 Use override value [/edwet...   
77  DIRECTOR> VAR_27028 Use override value [/edwet...   
78  DIRECTOR> VAR_27028 Use override value [/edwet...   
79  DIRECTOR> VAR_27028 Use override value [/edwet...   
80  DIRECTOR> VAR_27028 Use override value [/edwet...   

                                  filename  \
0      localhost_access_log.2015-03-18.txt   
1      localhost_access_log.2015-03-24.txt   
2      localhost_access_log.2015-03-25.txt   
3      localhost_access_log.2015-03-26.txt   
4      localhost_access_log.2015-03-28.txt   
5      localhost_access_log.2015-03-31.txt   
6      localhost_access_log.2015-04-01.txt   
7      localhost_access_log.2015-04-07.txt   
8      localhost_access_log.2015-04-09.txt   
9      localhost_access_log.2015-04-16.txt   
10     

In [42]:
df_final = df_final.reset_index(drop=True)

In [43]:
df_final.drop(columns=['filename'])

lines  \
0    0:0:0:0:0:0:0:1 - - [18/Mar/2015:09:51:32 +053...   
1    10.23.225.247 - - [24/Mar/2015:12:40:00 +0530]...   
2    10.23.225.247 - - [25/Mar/2015:12:15:07 +0530]...   
3    172.16.192.94 - - [26/Mar/2015:00:08:32 +0530]...   
4    10.23.225.168 - - [28/Mar/2015:10:29:08 +0530]...   
5    10.23.227.11 - - [31/Mar/2015:01:06:43 +0530] ...   
6    172.19.132.26 - - [01/Apr/2015:09:26:25 +0530]...   
7    10.53.99.12 - - [07/Apr/2015:12:19:23 +0530] "...   
8    10.53.50.32 - - [09/Apr/2015:09:46:50 +0530] "...   
9    10.53.50.151 - - [16/Apr/2015:10:16:22 +0530] ...   
10   10.53.50.151 - - [17/Apr/2015:10:16:28 +0530] ...   
11   10.53.50.151 - - [20/Apr/2015:10:16:21 +0530] ...   
12   10.56.161.93 - - [22/Apr/2015:08:41:51 +0530] ...   
13   172.16.192.94 - - [28/Apr/2015:03:07:50 +0530]...   
14   10.53.254.13 - - [29/Apr/2015:11:56:53 +0530] ...   
15   172.17.2.111 - - [30/Apr/2015:11:27:04 +0530] ...   
16   172.17.1.150 - - [04/May/2015:10:02:58 +0530] ...   
17   10.53.50.50 - - [06/May/2015:09:41:14 +0530] "...   
18   10.53.254.7 - - [07/May/2015:12:52:53 +0530] "...   
19   172.16.192.94 - - [12/May/2015:05:29:22 +0530]...   
20   172.16.192.94 - - [13/May/2015:05:36:57 +0530]...   
21   172.16.192.94 - - [15/May/2015:05:14:10 +0530]...   
22   10.56.160.44 - - [19/May/2015:09:36:36 +0530] ...   
23   10.53.254.5 - - [20/May/2015:09:09:03 +0530] "...   
24   10.53.50.50 - - [21/May/2015:09:39:58 +0530] "...   
25   172.16.192.94 - - [25/May/2015:02:09:43 +0530]...   
26   172.16.192.94 - - [26/May/2015:02:12:50 +0530]...   
27   172.16.192.94 - - [28/May/2015:02:40:59 +0530]...   
28   172.16.192.94 - - [29/May/2015:02:48:47 +0530]...   
29   10.53.50.77 - - [03/Jun/2015:11:56:39 +0530] "...   
..                                                 ...   
237  DIRECTOR> VAR_27028 Use override value [/edwet...   
238  DIRECTOR> VAR_27028 Use override value [/edwet...   
239  DIRECTOR> VAR_27028 Use override value [/edwet...   
240  DIRECTOR> VAR_27028 Use override value [/edwet...   
241  DIRECTOR> VAR_27028 Use override value [/edwet...   
242  DIRECTOR> VAR_27028 Use override value [/edwet...   
243  DIRECTOR> VAR_27028 Use override value [/edwet...   
244  DIRECTOR> VAR_27028 Use override value [/edwet...   
245  DIRECTOR> VAR_27028 Use override value [/edwet...   
246  DIRECTOR> VAR_27028 Use override value [/edwet...   
247  DIRECTOR> VAR_27028 Use override value [/edwet...   
248  DIRECTOR> VAR_27028 Use override value [/edwet...   
249  DIRECTOR> VAR_27093 Info: Override variable [m...   
250  DIRECTOR> VAR_27028 Use override value [/edwet...   
251  DIRECTOR> VAR_27028 Use override value [/edwet...   
252  DIRECTOR> VAR_27028 Use override value [/edwet...   
253  DIRECTOR> VAR_27028 Use override value [/edwet...   
254  DIRECTOR> VAR_27028 Use override value [/edwet...   
255  DIRECTOR> VAR_27028 Use override value [/edwet...   
256  DIRECTOR> VAR_27028 Use override value [/edwet...   
257  DIRECTOR> VAR_27028 Use override value [/edwet...   
258  DIRECTOR> VAR_27028 Use override value [/edwet...   
259  DIRECTOR> VAR_27028 Use override value [/edwet...   
260  DIRECTOR> VAR_27028 Use override value [/edwet...   
261  DIRECTOR> VAR_27028 Use override value [/edwet...   
262  DIRECTOR> VAR_27028 Use override value [/edwet...   
263  DIRECTOR> VAR_27028 Use override value [/edwet...   
264  DIRECTOR> VAR_27028 Use override value [/edwet...   
265  DIRECTOR> VAR_27028 Use override value [/edwet...   
266  DIRECTOR> VAR_27028 Use override value [/edwet...   

                                            clean_line label  
0    2015 0530 HTTP 11444 2015 0530 scm16mar tureg ...     1  
1    2015 0530 scm16Mar HTTP 2015 0530 HTTP 2015 05...     1  
2    2015 0530 HTTP 2015 0530 HTTP 2015 0530 HTTP 2...     1  
3    2015 0530 HTTP 11424 2015 0530 HTTP 11424 2015...     1  
4    2015 0530 dash HTTP 9496 2015 0530 5Ccss 5CCC ...     1  
5    2015 0530 tureg HTTP 4339 2015 0530 tureg HTTP...     1  
6    2015 0

###  Data Preprocessing and Apply ML Model

In [44]:
# split the dataset into training and validation datasets 
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(df_final['clean_line'], df_final['label'])

In [45]:
valid_y

11     1
192    4
61     1
123    3
13     1
22     1
39     1
65     1
108    3
175    3
179    3
226    4
31     1
131    3
245    4
180    3
119    3
241    4
140    3
27     1
223    4
148    3
71     1
113    3
183    3
146    3
163    3
253    4
29     1
114    3
      ..
53     1
128    3
203    4
247    4
89     2
91     2
7      1
243    4
182    3
8      1
176    3
15     1
52     1
73     1
222    4
4      1
17     1
82     2
232    4
86     2
69     1
167    3
206    4
104    2
177    3
159    3
147    3
101    2
184    3
228    4
Name: label, Length: 67, dtype: object

In [46]:
# label encode the target variable 
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)

In [47]:
valid_y

array([0, 3, 0, 2, 0, 0, 0, 0, 2, 2, 2, 3, 0, 2, 3, 2, 2, 3, 2, 0, 3, 2,
       0, 2, 2, 2, 2, 3, 0, 2, 2, 2, 1, 3, 0, 0, 2, 0, 2, 3, 3, 1, 1, 0,
       3, 2, 0, 2, 0, 0, 0, 3, 0, 0, 1, 3, 1, 0, 2, 3, 1, 2, 2, 2, 1, 2,
       3], dtype=int64)

In [48]:
# create a count vectorizer object 
count_vect = CountVectorizer(analyzer='word', token_pattern=r'\w{1,}')
count_vect.fit(df_final['clean_line'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='\\w{1,}', tokenizer=None,
        vocabulary=None)

In [49]:
# transform the training and validation data using count vectorizer object
xtrain_count =  count_vect.transform(train_x)
xvalid_count =  count_vect.transform(valid_x)

In [50]:
xtrain_count

<200x204847 sparse matrix of type '<class 'numpy.int64'>'
	with 67051 stored elements in Compressed Sparse Row format>

In [51]:
print(xtrain_count)

  (0, 3328)	1
  (0, 8115)	1
  (0, 20577)	1
  (0, 24663)	1
  (0, 27348)	1
  (0, 27762)	1
  (0, 36414)	1
  (0, 40214)	1
  (0, 61923)	1
  (0, 66505)	1
  (0, 68292)	1
  (0, 79590)	1
  (0, 105109)	8
  (0, 105153)	1
  (0, 105194)	442
  (0, 147072)	1
  (0, 147774)	1
  (0, 174433)	17
  (0, 175235)	18
  (0, 196175)	1
  (0, 197280)	35
  (0, 197298)	9
  (0, 197602)	255
  (0, 197672)	551
  (0, 197693)	57
  :	:
  (199, 201828)	21
  (199, 201829)	3
  (199, 202485)	2
  (199, 202732)	19
  (199, 202869)	19
  (199, 202960)	4
  (199, 202967)	1
  (199, 203119)	19
  (199, 203338)	19
  (199, 203357)	19
  (199, 203367)	19
  (199, 203374)	19
  (199, 203434)	1
  (199, 203580)	8
  (199, 203582)	1
  (199, 203585)	2
  (199, 203681)	19
  (199, 203690)	19
  (199, 203696)	95
  (199, 203705)	76
  (199, 203707)	156
  (199, 203729)	1
  (199, 203734)	3
  (199, 204032)	38
  (199, 204115)	57


In [52]:
# print(count_vect.vocabulary_)
#count_vect.vocabulary_
#print count vector in array format
#print(xtrain_count.toarray())

In [53]:
# word level tf-idf
tfidf_vect = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=5000)
tfidf_vect.fit(df_final['clean_line'])
xtrain_tfidf =  tfidf_vect.transform(train_x)
xvalid_tfidf =  tfidf_vect.transform(valid_x)

In [54]:
#print(xtrain_tfidf)
print(xvalid_tfidf)

  (0, 4923)	0.003163399618416185
  (0, 4904)	0.0032558503032673524
  (0, 4900)	0.005441009871762024
  (0, 4852)	0.006572586416832542
  (0, 4851)	0.007365187573116806
  (0, 4827)	0.017045493958308
  (0, 4760)	0.006338971446181174
  (0, 4758)	0.001810871676634477
  (0, 4739)	0.005789673834207329
  (0, 4700)	0.008262326625546294
  (0, 4695)	0.0029778434534289393
  (0, 4694)	0.003647503481129649
  (0, 4691)	0.015138855779571527
  (0, 4690)	0.033357087822916166
  (0, 4687)	0.026444400238189957
  (0, 4684)	0.004341133737689803
  (0, 4681)	0.013158710312046736
  (0, 4680)	0.011283954854283075
  (0, 4550)	0.0038010076097818816
  (0, 4474)	0.0022372373731298816
  (0, 4425)	0.0015229934382164998
  (0, 4203)	0.0017632603720331465
  (0, 4195)	0.002574096859288314
  (0, 4194)	0.008966130533829515
  (0, 4186)	0.0030983724845798605
  :	:
  (66, 655)	0.00700724697176185
  (66, 580)	0.14959974892437347
  (66, 524)	0.008024539857142387
  (66, 523)	0.008116447283388836
  (66, 522)	0.006674650341538732
  

In [55]:
# ngram level tf-idf 
tfidf_vect_ngram = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', ngram_range=(2,3), max_features=5000)
tfidf_vect_ngram.fit(df_final['clean_line'])
xtrain_tfidf_ngram =  tfidf_vect_ngram.transform(train_x)
xvalid_tfidf_ngram =  tfidf_vect_ngram.transform(valid_x)

In [56]:
print(xtrain_tfidf_ngram)

  (0, 4920)	0.006929777461645395
  (0, 4919)	0.004468578300030923
  (0, 4918)	0.004468578300030923
  (0, 4917)	0.004468578300030923
  (0, 4916)	0.004468578300030923
  (0, 4915)	0.004468578300030923
  (0, 4506)	0.006929777461645395
  (0, 4505)	0.004468578300030923
  (0, 4504)	0.004468578300030923
  (0, 4503)	0.004468578300030923
  (0, 4502)	0.004468578300030923
  (0, 4500)	0.03087832941529246
  (0, 4497)	0.004995939992386671
  (0, 4496)	0.004995939992386671
  (0, 4495)	0.04830534233955032
  (0, 4494)	0.04830534233955032
  (0, 4368)	0.14155163311762234
  (0, 4367)	0.14155163311762234
  (0, 4366)	0.009740684862962675
  (0, 4365)	0.009740684862962675
  (0, 4364)	0.01948136972592535
  (0, 4340)	0.012967601711691893
  (0, 4339)	0.012967601711691893
  (0, 4245)	0.14155163311762234
  (0, 4244)	0.14155163311762234
  :	:
  (199, 932)	0.024639651315400423
  (199, 930)	0.024639651315400423
  (199, 929)	0.0020880593867846475
  (199, 924)	0.024487969902409833
  (199, 920)	0.024639651315400423
  (199

In [57]:
print(xvalid_tfidf_ngram)

  (0, 4976)	0.003119801411505795
  (0, 4945)	0.003210977934198099
  (0, 4944)	0.005788433280023788
  (0, 4883)	0.016810571703099474
  (0, 4791)	0.002421042390898195
  (0, 4571)	0.0042824100917326375
  (0, 4570)	0.03931287368768646
  (0, 4569)	0.031270602454192775
  (0, 4409)	0.0020098225633885655
  (0, 4408)	0.002316348298673465
  (0, 4407)	0.0037486218424970623
  (0, 4202)	0.003210977934198099
  (0, 4201)	0.003210977934198099
  (0, 3880)	0.0011581741493367325
  (0, 3863)	0.003210977934198099
  (0, 3832)	0.0021894553938734966
  (0, 3831)	0.0012975520972203951
  (0, 3830)	0.0030556704864251653
  (0, 3819)	0.007722412609130078
  (0, 3740)	0.0021728566577639613
  (0, 3739)	0.0030766712813305014
  (0, 3506)	0.1022354451016658
  (0, 3505)	0.1022354451016658
  (0, 3503)	0.11094977324045655
  (0, 3502)	0.1022354451016658
  :	:
  (66, 484)	0.16297821712624594
  (66, 483)	0.16297821712624594
  (66, 475)	0.16607569854620957
  (66, 472)	0.11836802782705602
  (66, 461)	0.03739994804605283
  (66, 4

In [58]:
df_final['char_count'] = df_final['clean_line'].apply(len)
df_final['word_count'] = df_final['clean_line'].apply(lambda x: len(x.split()))
df_final['word_density'] = df_final['char_count'] / (df_final['word_count']+1)
df_final['punctuation_count'] = df_final['clean_line'].apply(lambda x: len("".join(_ for _ in x if _ in string.punctuation))) 
df_final['title_word_count'] = df_final['clean_line'].apply(lambda x: len([wrd for wrd in x.split() if wrd.istitle()]))
df_final['upper_case_word_count'] = df_final['clean_line'].apply(lambda x: len([wrd for wrd in x.split() if wrd.isupper()]))

In [59]:
# train a LDA Model
#lda_model = decomposition.LatentDirichletAllocation(n_components=20, learning_method='online', max_iter=20)
#X_topics = lda_model.fit_transform(xtrain_count)
#topic_word = lda_model.components_ 
#vocab = count_vect.get_feature_names()

In [60]:
# view the topic models
#n_top_words = 10
#topic_summaries = []
#for i, topic_dist in enumerate(topic_word):
#    topic_words = numpy.array(vocab)[numpy.argsort(topic_dist)][:-(n_top_words+1):-1]
#    topic_summaries.append(' '.join(topic_words))

In [61]:
def train_model(classifier, feature_vector_train, label, feature_vector_valid, is_neural_net=False):
    # fit the training dataset on the classifier
    classifier.fit(feature_vector_train, label)
    
    # predict the labels on validation dataset
    predictions = classifier.predict(feature_vector_valid)
    
    if is_neural_net:
        predictions = predictions.argmax(axis=-1)
    
    return metrics.accuracy_score(predictions, valid_y)

In [62]:
# Naive Bayes on Count Vectors
accuracy = train_model(naive_bayes.MultinomialNB(), xtrain_count, train_y, xvalid_count)
print("NB, Count Vectors: ", accuracy)

# Naive Bayes on Word Level TF IDF Vectors
accuracy = train_model(naive_bayes.MultinomialNB(), xtrain_tfidf, train_y, xvalid_tfidf)
print("NB, WordLevel TF-IDF: ", accuracy)

# Naive Bayes on Ngram Level TF IDF Vectors
accuracy = train_model(naive_bayes.MultinomialNB(), xtrain_tfidf_ngram, train_y, xvalid_tfidf_ngram)
print("NB, N-Gram Vectors: ", accuracy) 



NB, Count Vectors:  1.0
NB, WordLevel TF-IDF:  0.9850746268656716
NB, N-Gram Vectors:  1.0


## NB: Get predictions for NB, WordLevel TF-IDF

In [63]:
clas_NB_wordlevel_tfidf = naive_bayes.MultinomialNB().fit(xtrain_tfidf, train_y)

predictions_NB_wordlevel_tfidf = clas_NB_wordlevel_tfidf.predict(xvalid_tfidf)

In [64]:
#train_accuracy
metrics.accuracy_score(train_y, clas_NB_wordlevel_tfidf.predict(xtrain_tfidf))

0.975

In [65]:
#test_accuracy
accuracy_NB_wordlevel_tfidf = metrics.accuracy_score(predictions_NB_wordlevel_tfidf,valid_y)
accuracy_NB_wordlevel_tfidf

0.9850746268656716

In [66]:
metrics.confusion_matrix(valid_y, predictions_NB_wordlevel_tfidf)

array([[21,  0,  0,  0],
       [ 0,  6,  1,  0],
       [ 0,  0, 25,  0],
       [ 0,  0,  0, 14]], dtype=int64)

In [67]:
predictions_NB_wordlevel_tfidf

array([0, 3, 0, 2, 0, 0, 0, 0, 2, 2, 2, 3, 0, 2, 3, 2, 2, 3, 2, 0, 3, 2,
       0, 2, 2, 2, 2, 3, 0, 2, 2, 2, 2, 3, 0, 0, 2, 0, 2, 3, 3, 1, 1, 0,
       3, 2, 0, 2, 0, 0, 0, 3, 0, 0, 1, 3, 1, 0, 2, 3, 1, 2, 2, 2, 1, 2,
       3], dtype=int64)

## NB: Get predictions for NB, Count Vectors

In [68]:
clas_NB_countvectors = naive_bayes.MultinomialNB().fit(xtrain_count, train_y)

predictions_NB_countvectors = clas_NB_countvectors.predict(xvalid_count)

predictions_NB_countvectors

array([0, 3, 0, 2, 0, 0, 0, 0, 2, 2, 2, 3, 0, 2, 3, 2, 2, 3, 2, 0, 3, 2,
       0, 2, 2, 2, 2, 3, 0, 2, 2, 2, 1, 3, 0, 0, 2, 0, 2, 3, 3, 1, 1, 0,
       3, 2, 0, 2, 0, 0, 0, 3, 0, 0, 1, 3, 1, 0, 2, 3, 1, 2, 2, 2, 1, 2,
       3], dtype=int64)

In [69]:
#train_accuracy
metrics.accuracy_score(train_y, clas_NB_countvectors.predict(xtrain_count))

1.0

In [70]:
#test_accuracy
accuracy_NB_countvectors = metrics.accuracy_score(predictions_NB_countvectors,valid_y)
accuracy_NB_countvectors

1.0

In [71]:
metrics.confusion_matrix(valid_y, predictions_NB_countvectors)

array([[21,  0,  0,  0],
       [ 0,  7,  0,  0],
       [ 0,  0, 25,  0],
       [ 0,  0,  0, 14]], dtype=int64)

# NB: Get Predictions for Ngram Level TFIDF

In [72]:
clas_NB_ngram_tfidf = naive_bayes.MultinomialNB().fit(xtrain_tfidf_ngram, train_y)

predictions_NB_ngram_tfidf = clas_NB_ngram_tfidf.predict(xvalid_tfidf_ngram)

predictions_NB_ngram_tfidf

array([0, 3, 0, 2, 0, 0, 0, 0, 2, 2, 2, 3, 0, 2, 3, 2, 2, 3, 2, 0, 3, 2,
       0, 2, 2, 2, 2, 3, 0, 2, 2, 2, 1, 3, 0, 0, 2, 0, 2, 3, 3, 1, 1, 0,
       3, 2, 0, 2, 0, 0, 0, 3, 0, 0, 1, 3, 1, 0, 2, 3, 1, 2, 2, 2, 1, 2,
       3], dtype=int64)

In [73]:
#train_accuracy
metrics.accuracy_score(train_y, clas_NB_ngram_tfidf.predict(xtrain_tfidf_ngram))

1.0

In [74]:
#test_accuracy
accuracy_NB_ngram_tfidf = metrics.accuracy_score(predictions_NB_ngram_tfidf,valid_y)
accuracy_NB_ngram_tfidf

1.0

In [75]:
metrics.confusion_matrix(valid_y, predictions_NB_ngram_tfidf,labels=(0,1,2,3))

array([[21,  0,  0,  0],
       [ 0,  7,  0,  0],
       [ 0,  0, 25,  0],
       [ 0,  0,  0, 14]], dtype=int64)

## Random Forest ## 

In [76]:
# RF on Count Vectors
accuracy = train_model(ensemble.RandomForestClassifier(), xtrain_count, train_y, xvalid_count)
print("RF, Count Vectors: ", accuracy)

# RF on Word Level TF IDF Vectors
accuracy = train_model(ensemble.RandomForestClassifier(), xtrain_tfidf, train_y, xvalid_tfidf)
print("RF, WordLevel TF-IDF: ", accuracy)

### RF on Ngram level TF IDF Vectors

accuracy = train_model(ensemble.RandomForestClassifier(), xtrain_tfidf_ngram, train_y, xvalid_tfidf_ngram)
print("RF, N-Gram Vectors: ", accuracy) 


### RF on Ngram level TF IDF Vectors

RF, Count Vectors:  0.9850746268656716
RF, WordLevel TF-IDF:  0.9850746268656716
RF, N-Gram Vectors:  0.9850746268656716


## RF: Get Predictions from Word Level

In [77]:
clas_RF_wordlevel_tfidf = ensemble.RandomForestClassifier().fit(xtrain_tfidf, train_y)

predictions_RF_wordlevel_tfidf = clas_RF_wordlevel_tfidf.predict(xvalid_tfidf)

In [78]:
#train_accuracy
metrics.accuracy_score(train_y, clas_RF_wordlevel_tfidf.predict(xtrain_tfidf))

1.0

In [79]:
#test_accuracy
accuracy_RF_wordlevel_tfidf = metrics.accuracy_score(predictions_RF_wordlevel_tfidf,valid_y)
accuracy_RF_wordlevel_tfidf

0.9850746268656716

In [80]:
metrics.confusion_matrix(valid_y, predictions_RF_wordlevel_tfidf,labels=(0,1,2,3))

array([[21,  0,  0,  0],
       [ 0,  7,  0,  0],
       [ 0,  0, 25,  0],
       [ 1,  0,  0, 13]], dtype=int64)

In [81]:
predictions_RF_wordlevel_tfidf

array([0, 3, 0, 2, 0, 0, 0, 0, 2, 2, 2, 3, 0, 2, 3, 2, 2, 3, 2, 0, 3, 2,
       0, 2, 2, 2, 2, 3, 0, 2, 2, 2, 1, 3, 0, 0, 2, 0, 2, 3, 3, 1, 1, 0,
       3, 2, 0, 2, 0, 0, 0, 0, 0, 0, 1, 3, 1, 0, 2, 3, 1, 2, 2, 2, 1, 2,
       3], dtype=int64)

### RF: Get Predictions from Count Vector

In [82]:
clas_RF_countvector = ensemble.RandomForestClassifier().fit(xtrain_count, train_y)

predictions_RF_countvector = clas_RF_countvector.predict(xvalid_count)

predictions_RF_countvector

array([0, 3, 0, 2, 0, 0, 0, 0, 2, 2, 2, 3, 0, 2, 3, 2, 2, 3, 2, 0, 3, 2,
       0, 2, 2, 2, 2, 3, 0, 2, 2, 2, 1, 3, 0, 0, 2, 0, 2, 3, 3, 1, 1, 0,
       3, 2, 2, 2, 0, 0, 0, 3, 0, 0, 1, 3, 1, 0, 2, 3, 1, 2, 2, 2, 1, 2,
       3], dtype=int64)

In [83]:
#train_accuracy
metrics.accuracy_score(train_y, clas_RF_countvector.predict(xtrain_count))

1.0

In [84]:
#test_accuracy
accuracy_RF_countvector = metrics.accuracy_score(predictions_RF_countvector,valid_y)
accuracy_RF_countvector

0.9850746268656716

In [85]:
metrics.confusion_matrix(valid_y, predictions_RF_countvector)

array([[20,  0,  1,  0],
       [ 0,  7,  0,  0],
       [ 0,  0, 25,  0],
       [ 0,  0,  0, 14]], dtype=int64)

# RF: Get Predictions for Ngram Level TFIDF

In [86]:
clas_RF_ngram_tfidf = ensemble.RandomForestClassifier().fit(xtrain_tfidf_ngram, train_y)
predictions_RF_ngram_tfidf = clas_RF_ngram_tfidf.predict(xvalid_tfidf_ngram)


In [87]:
#train_accuracy
metrics.accuracy_score(train_y, clas_RF_ngram_tfidf.predict(xtrain_tfidf_ngram))

1.0

In [88]:
#test_accuracy
accuracy_RF_ngram_tfidf = metrics.accuracy_score(predictions_RF_ngram_tfidf,valid_y)
accuracy_RF_ngram_tfidf

0.9850746268656716

In [89]:
metrics.confusion_matrix(valid_y, predictions_RF_ngram_tfidf,labels=(0,1,2,3))

array([[21,  0,  0,  0],
       [ 0,  7,  0,  0],
       [ 0,  0, 25,  0],
       [ 1,  0,  0, 13]], dtype=int64)

# Decision tree

In [90]:
accuracy_DT_ngram_tfidf = train_model(tree.DecisionTreeClassifier(criterion='gini'), xtrain_tfidf_ngram, train_y, xvalid_tfidf_ngram)
print("RF-Information Gain, N-Gram Vectors: ", accuracy) 

RF-Information Gain, N-Gram Vectors:  0.9850746268656716


# SVM 

In [91]:
# SVM on Count Vectors
accuracy = train_model(svm.SVC(), xtrain_count, train_y, xvalid_count)
print("SVM, Count Vectors: ", accuracy)

# SVM on Word Level TF IDF Vectors
accuracy = train_model(svm.SVC(), xtrain_tfidf, train_y, xvalid_tfidf)
print("SVM, WordLevel TF-IDF: ", accuracy)

# SVM on Ngram Level TF IDF Vectors
accuracy = train_model(svm.SVC(), xtrain_tfidf_ngram, train_y, xvalid_tfidf_ngram)
print("SVM, N-Gram Vectors: ", accuracy)

SVM, Count Vectors:  0.8805970149253731
SVM, WordLevel TF-IDF:  0.208955223880597
SVM, N-Gram Vectors:  0.208955223880597


### SVM: Get predictions for SVM, tfidf word level

In [92]:
clas_SVM_wordlevel_tfidf = svm.SVC().fit(xtrain_tfidf, train_y)

predictions_SVM_wordlevel_tfidf = clas_SVM_wordlevel_tfidf.predict(xvalid_tfidf)

In [93]:
#train_accuracy
metrics.accuracy_score(train_y, clas_SVM_wordlevel_tfidf.predict(xtrain_tfidf))

0.335

In [94]:
#test_accuracy
accuracy_SVM_wordlevel_tfidf = metrics.accuracy_score(predictions_SVM_wordlevel_tfidf,valid_y)
accuracy_SVM_wordlevel_tfidf

0.208955223880597

In [95]:
metrics.confusion_matrix(valid_y, predictions_SVM_wordlevel_tfidf)

array([[ 0,  0,  0, 21],
       [ 0,  0,  0,  7],
       [ 0,  0,  0, 25],
       [ 0,  0,  0, 14]], dtype=int64)

In [96]:
predictions_SVM_wordlevel_tfidf

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3], dtype=int64)

## SVM: Get predictions for NB, Count Vectors

In [97]:
clas_SVM_countvectors = svm.SVC().fit(xtrain_count, train_y)

predictions_SVM_countvectors = clas_SVM_countvectors.predict(xvalid_count)

predictions_SVM_countvectors

array([0, 3, 2, 2, 0, 0, 0, 0, 2, 2, 2, 3, 0, 2, 3, 2, 2, 2, 2, 0, 3, 2,
       0, 2, 2, 2, 2, 3, 0, 2, 2, 2, 1, 3, 0, 2, 2, 2, 2, 3, 3, 1, 1, 2,
       3, 2, 2, 2, 0, 0, 0, 2, 0, 0, 2, 3, 1, 0, 2, 3, 1, 2, 2, 2, 1, 2,
       3], dtype=int64)

In [98]:
#train_accuracy
metrics.accuracy_score(train_y, clas_SVM_countvectors.predict(xtrain_count))

1.0

In [99]:
#test_accuracy
accuracy_SVM_countvectors = metrics.accuracy_score(predictions_SVM_countvectors,valid_y)

In [100]:
accuracy_SVM_countvectors 

0.8805970149253731

In [101]:
metrics.confusion_matrix(valid_y, predictions_SVM_countvectors)

array([[16,  0,  5,  0],
       [ 0,  6,  1,  0],
       [ 0,  0, 25,  0],
       [ 0,  0,  2, 12]], dtype=int64)

# SVM: Get Predictions for Ngram Level TFIDF

In [102]:
clas_SVM_ngram_tfidf = svm.SVC().fit(xtrain_tfidf_ngram, train_y)

predictions_SVM_ngram_tfidf = clas_SVM_ngram_tfidf.predict(xvalid_tfidf_ngram)

predictions_SVM_ngram_tfidf

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3], dtype=int64)

In [103]:
#train_accuracy
metrics.accuracy_score(train_y, clas_SVM_ngram_tfidf.predict(xtrain_tfidf_ngram))

0.335

In [104]:
#test_accuracy
accuracy_SVM_ngram_tfidf = metrics.accuracy_score(predictions_SVM_ngram_tfidf,valid_y)
accuracy_SVM_ngram_tfidf 

0.208955223880597

In [105]:
metrics.confusion_matrix(valid_y, predictions_SVM_ngram_tfidf,labels=(0,1,2,3))

array([[ 0,  0,  0, 21],
       [ 0,  0,  0,  7],
       [ 0,  0,  0, 25],
       [ 0,  0,  0, 14]], dtype=int64)

### Pick the Best model from above and map predictions to actual labels

In [106]:
###

In [107]:
df_acc_list = [accuracy_NB_wordlevel_tfidf,accuracy_NB_countvectors,accuracy_NB_ngram_tfidf,
               accuracy_RF_wordlevel_tfidf,accuracy_RF_countvector,accuracy_RF_ngram_tfidf,
               accuracy_SVM_wordlevel_tfidf,accuracy_SVM_countvectors,accuracy_SVM_ngram_tfidf]

In [108]:
df_acc_dict = dict({'accuracy_NB_wordlevel_tfidf':accuracy_NB_wordlevel_tfidf,
                    'accuracy_NB_countvectors': accuracy_NB_countvectors,
                    'accuracy_NB_ngram_tfidf' : accuracy_NB_ngram_tfidf,
                    'accuracy_RF_wordlevel_tfidf' : accuracy_RF_wordlevel_tfidf,
                    'accuracy_RF_countvector' : accuracy_RF_countvector,
                    'accuracy_RF_ngram_tfidf' : accuracy_RF_ngram_tfidf,
                    'accuracy_SVM_wordlevel_tfidf': accuracy_SVM_wordlevel_tfidf,
                    'accuracy_SVM_countvectors': accuracy_SVM_countvectors,
                    'accuracy_SVM_ngram_tfidf' : accuracy_SVM_ngram_tfidf
                   })

In [109]:
df_acc_desc_list =  ['accuracy_NB_wordlevel_tfidf','accuracy_NB_countvectors','accuracy_NB_ngram_tfidf',
                    'accuracy_RF_wordlevel_tfidf',
                    'accuracy_RF_countvector' ,
                    'accuracy_RF_ngram_tfidf' ,
                    'accuracy_SVM_wordlevel_tfidf',
                    'accuracy_SVM_countvectors',
                    'accuracy_SVM_ngram_tfidf' 
                    ]

In [112]:
df_accuracy = pd.DataFrame({'Accuracy':df_acc_list,'Accuracy_desc':df_acc_desc_list})

In [113]:
df_accuracy

Accuracy                 Accuracy_desc
0  0.985075   accuracy_NB_wordlevel_tfidf
1  1.000000      accuracy_NB_countvectors
2  1.000000       accuracy_NB_ngram_tfidf
3  0.985075   accuracy_RF_wordlevel_tfidf
4  0.985075       accuracy_RF_countvector
5  0.985075       accuracy_RF_ngram_tfidf
6  0.208955  accuracy_SVM_wordlevel_tfidf
7  0.880597     accuracy_SVM_countvectors
8  0.208955      accuracy_SVM_ngram_tfidf

In [114]:
df_best_accuracy = df_accuracy[df_accuracy['Accuracy']==df_accuracy['Accuracy'].max()]

In [115]:
df_best_accuracy

Accuracy             Accuracy_desc
1       1.0  accuracy_NB_countvectors
2       1.0   accuracy_NB_ngram_tfidf

In [116]:
df_best_accuracy['Accuracy_c'] = df_best_accuracy['Accuracy_desc'].apply(lambda x: 1 if x == 'accuracy_NB_ngram_tfidf'
                                                                        else 2 if x == 'accuracy_RF_ngram_tfidf'
                                                                        else 3 if x == 'accuracy_SVM_ngram_tfidf'
                                                                        else 4 if x == 'accuracy_NB_wordlevel_tfidf'
                                                                        else 5 if x == 'accuracy_RF_wordlevel_tfidf' 
                                                                        else 6 if x == 'accuracy_SVM_wordlevel_tfidf'
                                                                        else 7 if x == 'accuracy_NB_countvectors'
                                                                        else 8 if x == 'accuracy_RF_countvector' 
                                                                        else 9 if x == 'accuracy_SVM_countvectors'
                                                                        else 10                                                                      
                                                                         
                                                             
                                                             )

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [117]:
df_best_accuracy['Accuracy_c']

1    7
2    1
Name: Accuracy_c, dtype: int64

In [118]:
df_accuracy_final = df_best_accuracy.sort_values('Accuracy_c', ascending=True).head(1)
df_accuracy_final 

Accuracy            Accuracy_desc  Accuracy_c
2       1.0  accuracy_NB_ngram_tfidf           1

In [119]:
#filename = 'finalized_train_model.sav'
#filename_tfidf_model = 'tfidf_train_model.sav'

In [120]:
#pickle.dump(clas_NB_ngram_tfidf, open(filename, 'wb'))
#pickle.dump(tfidf_vect_ngram, open(filename_tfidf_ngram, 'wb'))

In [121]:
df_predictions = pd.DataFrame() 
if df_accuracy_final['Accuracy_c'].any() == 1:
    df_predictions = pd.DataFrame({'Predictions':predictions_NB_ngram_tfidf})
    pickle.dump(clas_NB_ngram_tfidf, open('finalized_train_model.sav', 'wb'))
    pickle.dump(tfidf_vect_ngram, open('tfidf_train_model.sav', 'wb'))
elif df_accuracy_final['Accuracy_c'].any() == 2:
    df_predictions = pd.DataFrame({'Predictions':predictions_RF_ngram_tfidf})
    pickle.dump(clas_RF_ngram_tfidf, open('finalized_train_model.sav', 'wb'))
    pickle.dump(tfidf_vect_ngram, open('tfidf_train_model.sav', 'wb'))
elif df_accuracy_final['Accuracy_c'].any() == 3:
    df_predictions = pd.DataFrame({'Predictions':predictions_SVM_ngram_tfidf})
    pickle.dump(clas_SVM_ngram_tfidf, open('finalized_train_model.sav', 'wb'))
    pickle.dump(tfidf_vect_ngram, open('tfidf_train_model.sav', 'wb'))
elif df_accuracy_final['Accuracy_c'].any() == 4:
    df_predictions = pd.DataFrame({'Predictions':predictions_NB_wordlevel_tfidf})
    pickle.dump(clas_NB_wordlevel_tfidf, open('finalized_train_model.sav', 'wb'))
    pickle.dump(tfidf_vect, open('tfidf_train_model.sav', 'wb'))
elif df_accuracy_final['Accuracy_c'].any() == 5:
    df_predictions = pd.DataFrame({'Predictions':predictions_RF_wordlevel_tfidf})
    pickle.dump(clas_RF_wordlevel_tfidf, open('finalized_train_model.sav', 'wb'))
    pickle.dump(tfidf_vect, open('tfidf_train_model.sav', 'wb'))
elif df_accuracy_final['Accuracy_c'].any() == 6:
    df_predictions = pd.DataFrame({'Predictions':predictions_SVM_wordlevel_tfidf})
    pickle.dump(clas_SVM_wordlevel_tfidf, open('finalized_train_model.sav', 'wb'))
    pickle.dump(tfidf_vect, open('tfidf_train_model.sav', 'wb'))
elif df_accuracy_final['Accuracy_c'].any() == 7:
    df_predictions = pd.DataFrame({'Predictions':predictions_NB_countvectors})
    pickle.dump(clas_NB_countvectors, open('finalized_train_model.sav', 'wb'))
    pickle.dump(count_vect, open('tfidf_train_model.sav', 'wb'))
elif df_accuracy_final['Accuracy_c'].any() == 8:
    df_predictions = pd.DataFrame({'Predictions':predictions_RF_countvector})
    pickle.dump(clas_RF_countvector, open('finalized_train_model.sav', 'wb'))
    pickle.dump(count_vect, open('tfidf_train_model.sav', 'wb'))
elif df_accuracy_final['Accuracy_c'].any() == 9:
    df_predictions = pd.DataFrame({'Predictions':predictions_SVM_countvectors})
    pickle.dump(clas_SVM_countvectors, open('finalized_train_model.sav', 'wb'))
    pickle.dump(count_vect, open('tfidf_train_model.sav', 'wb'))


In [122]:
#df_predictions

In [123]:
df_predictions['predicted_label'] = df_predictions['Predictions'].apply(lambda x: 'Localhost_access' if x== 0 else 'Localhost' if x == 1 
                                                                   else 'catalina' if x==2 
                                                                   else  'Informatica' if x==3 
                                                                   else  'NaN'
                                                             
                                                             )

In [124]:
df_predictions['actual_label_encoded'] = valid_y

In [125]:
df_predictions['actual_label'] = df_predictions['actual_label_encoded'].apply(lambda x: 'Localhost_access' if x== 0 else 'Localhost' if x == 1 
                                                                   else 'catalina' if x==2 
                                                                   else  'Informatica' if x==3 
                                                                   else  'NaN'
                                                             
                                                             )

In [126]:
df_predictions

Predictions   predicted_label  actual_label_encoded      actual_label
0             0  Localhost_access                     0  Localhost_access
1             3       Informatica                     3       Informatica
2             0  Localhost_access                     0  Localhost_access
3             2          catalina                     2          catalina
4             0  Localhost_access                     0  Localhost_access
5             0  Localhost_access                     0  Localhost_access
6             0  Localhost_access                     0  Localhost_access
7             0  Localhost_access                     0  Localhost_access
8             2          catalina                     2          catalina
9             2          catalina                     2          catalina
10            2          catalina                     2          catalina
11            3       Informatica                     3       Informatica
12            0  Localhost_access                     0  Localhost_access
13            2          catalina                     2          catalina
14            3       Informatica                     3       Informatica
15            2          catalina                     2          catalina
16            2          catalina                     2          catalina
17            3       Informatica                     3       Informatica
18            2          catalina                     2          catalina
19            0  Localhost_access                     0  Localhost_access
20            3       Informatica                     3       Informatica
21            2          catalina                     2          catalina
22            0  Localhost_access                     0  Localhost_access
23            2          catalina                     2          catalina
24            2          catalina                     2          catalina
25            2          catalina                     2          catalina
26            2          catalina                     2          catalina
27            3       Informatica                     3       Informatica
28            0  Localhost_access                     0  Localhost_access
29            2          catalina                     2          catalina
..          ...               ...                   ...               ...
37            0  Localhost_access                     0  Localhost_access
38            2          catalina                     2          catalina
39            3       Informatica                     3       Informatica
40            3       Informatica                     3       Informatica
41            1         Localhost                     1         Localhost
42            1         Localhost                     1         Localhost
43            0  Localhost_access                     0  Localhost_access
44            3       Informatica                     3       Informatica
45            2          catalina                     2          catalina
46            0  Localhost_access                     0  Localhost_access
47            2          catalina                     2          catalina
48            0  Localhost_access                     0  Localhost_access
49            0  Localhost_access                     0  Localhost_access
50            0  Localhost_access                     0  Localhost_access
51            3       Informatica                     3       Informatica
52            0  Localhost_access                     0  Localhost_access
53            0  Localhost_access                     0  Localhost_access
54            1         Localhost                     1         Localhost
55            3       Informatica                     3       Informatica
56            1         Localhost                     1         Localhost
57            0  Localhost_access                     0  Localhost_access
58            2          catalina                     2          catalina
59      

### Cross Validation 

In [127]:
# Necessary imports: 
from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn import metrics

In [128]:
# split the dataset into training and validation datasets 
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(df_final['clean_line'], df_final['label'],test_size=0)

In [129]:
len(train_y)

267

In [130]:
# label encode the target variable 
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)


In [131]:
# create a count vectorizer object 
count_vect = CountVectorizer(analyzer='word', token_pattern=r'\w{1,}')
count_vect.fit(df_final['clean_line'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='\\w{1,}', tokenizer=None,
        vocabulary=None)

In [132]:
# transform the training and validation data using count vectorizer object
xtrain_count =  count_vect.transform(train_x)


In [133]:
# word level tf-idf
tfidf_vect = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=5000)
tfidf_vect.fit(df_final['clean_line'])
xtrain_tfidf =  tfidf_vect.transform(train_x)


In [134]:
# ngram level tf-idf 
tfidf_vect_ngram = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', ngram_range=(2,3), max_features=5000)
tfidf_vect_ngram.fit(df_final['clean_line'])
xtrain_tfidf_ngram =  tfidf_vect_ngram.transform(train_x)


In [135]:
# Perform 6-fold cross validation
scores = cross_val_score(naive_bayes.MultinomialNB(), xtrain_tfidf_ngram, train_y, cv=6)

In [136]:
scores

array([1.        , 0.97826087, 1.        , 1.        , 1.        ,
       1.        ])

In [137]:
# Make cross validated predictions
predictions = cross_val_predict(naive_bayes.MultinomialNB(), xtrain_tfidf_ngram, train_y, cv=6)


In [138]:
predictions

array([3, 0, 0, 3, 0, 2, 2, 2, 0, 1, 0, 2, 3, 2, 3, 0, 0, 3, 2, 0, 2, 3,
       3, 0, 3, 3, 0, 2, 2, 3, 3, 2, 3, 3, 0, 2, 0, 2, 2, 3, 0, 3, 3, 2,
       1, 3, 0, 3, 3, 2, 3, 2, 2, 1, 3, 3, 1, 0, 1, 3, 1, 0, 3, 0, 3, 2,
       1, 0, 3, 3, 0, 0, 0, 3, 2, 3, 0, 1, 1, 2, 3, 2, 3, 1, 3, 0, 2, 3,
       0, 2, 1, 2, 0, 0, 3, 0, 2, 2, 2, 0, 2, 2, 0, 0, 3, 0, 0, 1, 1, 0,
       3, 2, 0, 2, 3, 0, 3, 3, 0, 2, 0, 0, 1, 2, 3, 0, 2, 3, 2, 1, 3, 0,
       2, 2, 3, 3, 0, 0, 0, 2, 3, 2, 2, 3, 3, 2, 3, 0, 2, 0, 1, 0, 3, 2,
       1, 2, 3, 2, 0, 2, 3, 1, 3, 0, 2, 3, 2, 2, 0, 1, 0, 2, 3, 3, 2, 3,
       3, 3, 3, 1, 3, 1, 1, 2, 2, 2, 0, 0, 0, 2, 1, 1, 3, 3, 3, 3, 3, 3,
       3, 0, 3, 3, 2, 2, 3, 2, 2, 2, 2, 0, 3, 3, 1, 0, 2, 0, 0, 0, 2, 0,
       3, 2, 2, 3, 3, 0, 2, 2, 0, 0, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 0, 2,
       1, 0, 1, 0, 0, 0, 0, 0, 3, 1, 3, 1, 0, 2, 2, 0, 0, 2, 1, 0, 0, 0,
       1, 2, 3], dtype=int64)

In [139]:
accuracy = metrics.accuracy_score(train_y, predictions)


In [140]:
accuracy

0.9962546816479401